In [26]:
import numpy as np 
import pandas as pd
np.random.seed(42)

## Exercise 1:
1. Create a NumPy array of size 4x3 and filled with random numbers from 10 to
98 (inclusive). Calculate the sum of all elements, the sum of each row and
each column.

In [74]:
np_random_array = np.random.randint(10,99,(4,3))
print(np_random_array)

print(f"Sum of all elements: {np_random_array.sum()}")
print(f"Sum of each row : {np_random_array.sum(axis=1)}")
print(f"Sum of each column : {np_random_array.sum(axis=0)}")

      

[[71 60 64]
 [73 12 60]
 [16 30 82]
 [48 27 13]]
Sum of all elements: 556
Sum of each row : [195 145 128  88]
Sum of each column : [208 129 219]


## Exercise 2:
1. Create a NumPy array of size 10 filled with random numbers from 0 to 10.
Count how many of them are even numbers.

In [134]:
random_array = np.random.randint(0,11,10)
print(random_array)
even = random_array % 2 == 0 
print(even.sum())

[ 7  0 10  0  1  1  5  6  4  0]
6


Exercise 3:
1. Create a NumPy array of size 100, filled with a sequence of numbers from 0
to 99.
2. Reshape this array into 10 rows and 10 columns.
 
3. Replace all values in the array which are greater than 50 with -1.

4. Calculate the sum of all elements in the array.

5. Calculate the mean of all elements in the array

In [180]:
np_array = np.arange(0,100)
print(np_array)
reshape_array = np_array.reshape(10,10)
reshape_array[reshape_array > 50] = -1
print(reshape_array)
print(f"Sum of all elements in the array : {reshape_array.sum()}")
print(f"Mean of all elements in the array : {reshape_array.mean()}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
Sum of all elements in the array : 1226
Mean of all elements in the array : 12.26


## Exercise 4:
1. Create an array of 10 elements with numbers between 0 -100 with the same
space between each element.
2. Generate a new array that has all values from the previous array that are
greater than 50 or lower than 20.
3. Reshape the array to a matrix array possible, (for example if its possible to
reshape the array to 4X3 matrix generate it)

In [74]:
lin_array = np.linspace(0, 100, 10)
print(f'First array : {lin_array}')
new_lin_array = lin_array[(lin_array > 50 )|(lin_array < 20)].copy()
print(f"New array : {new_lin_array} ")

def array_dreshaped(new_lin_array):
    try:
        new_lin_array =  new_lin_array.reshape(2,-1)  
    except ValueError:
        print(f"not possible to reshape a array whit : {new_lin_array.size} elements ")
    

array_dreshaped(new_lin_array)





First array : [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
New array : [  0.          11.11111111  55.55555556  66.66666667  77.77777778
  88.88888889 100.        ] 
not possible to reshape a array whit : 7 elements 


## Exercise 5:
1. Generate a matrix of 4x4 filled with 0, make sure the type of them is int type.
2. Change the first element, the last element and the center element to a
different random value between 10 - 100.

In [190]:
np_zeros = np.zeros((4,4),dtype= int)
print(np_zeros)


def change_values_random(matrix):
    indexes = [(0, 0), (3, 3)]
    matrix[1:3, 1] = np.random.randint(10, 101, size=(1,2))
    matrix[1:3, 2] = np.random.randint(10, 101, size=(1,2))
    for row, col in indexes:
        np_zeros[row,col] = np.random.randint(10,101)
    return np_zeros

change_values_random(np_zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[80,  0,  0,  0],
       [ 0, 38, 22,  0],
       [ 0, 45, 41,  0],
       [ 0,  0,  0, 68]])